In [160]:
from random import random
from random import randint

# Configuração Inicial

In [161]:
PASSOS = 1000000

A = [[0,0,.5,0,.5],
     [.5,0,.5,0,0],
     [0,.5,0,.5,0],
     [.5,0,0,0,.5],
     [0,0,1,0,0]]


#A = [[.02, 0.02, 0.88, 0.02, 0.02, 0.02, 0.02],
#     [0.02, 0.45, 0.45, 0.02, 0.02, 0.02, 0.02],
#     [0.31, 0.02, 0.31, 0.31, 0.02, 0.02, 0.02],
#     [0.02, 0.02, 0.02, 0.45, 0.45, 0.02, 0.02],
#     [0.02, 0.02, 0.02, 0.02, 0.02, 0.02, 0.88],
#     [0.02, 0.02, 0.02, 0.02, 0.02, 0.45, 0.45],
#     [0.02, 0.02, 0.02, 0.31, 0.31, 0.02, 0.31]]

p = .86

n = len(A)


In [162]:
DEF_SIZE = 50

def center(s,size=DEF_SIZE):
  tam = (size - len(s))//2
  return " "*tam+s

def print_line(char="=",size=DEF_SIZE):
  print(char*size)
  

# Fazendo o Random Walk

In [163]:
def pick_next(node,M=A,P=p):
  x = random()
  if x>P:
    #print("x",end="")
    return randint(0,n-1)
  else:
    total = M[node][0]
    y = random()
    for i in range(len(M[node])):
      if y <= total:
        return i
      total += M[node][i+1]
  print("hem?",x,i)


In [164]:
conta = [0]*n
node = randint(0,n-1)


for i in range(PASSOS):
  conta[node] += 1
  node = pick_next(node)
  #print(f"{node} ",end="")


In [165]:
conta2 = list(map(lambda x: x/PASSOS,conta))
total = sum(conta2)

result_rw = np.array(conta2)

print(result_rw)



[0.171072 0.165977 0.322361 0.166943 0.173647]


In [166]:
import numpy as np
from scipy.linalg import eig

In [167]:
Ar = np.array(A,float)


print(Ar)

[[0.  0.  0.5 0.  0.5]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.5 0.  0.5 0. ]
 [0.5 0.  0.  0.  0.5]
 [0.  0.  1.  0.  0. ]]


# Usando a matriz do Pagerank passo a passo

In [168]:
e = np.ones((n,1),float)
et = e.transpose()
E = e*et/n
print(e,et,E)

PrM = p*Ar+(1-p)*E

print(PrM)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]] [[1. 1. 1. 1. 1.]] [[0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]
 [0.2 0.2 0.2 0.2 0.2]]
[[0.028 0.028 0.458 0.028 0.458]
 [0.458 0.028 0.458 0.028 0.028]
 [0.028 0.458 0.028 0.458 0.028]
 [0.458 0.028 0.028 0.028 0.458]
 [0.028 0.028 0.888 0.028 0.028]]


In [169]:
xc = e / n
xct = et /n
PASSOSM = 400

for i in range(PASSOSM):
  xct = xct.dot(PrM)
  xct = xct/sum(sum(xct))
  
result_passo = np.array(xct)

print(result_passo)

[[0.17126332 0.16658525 0.32229129 0.16658525 0.17327489]]


# Usando os autovetores

In [170]:
xv = e / n

w,vl,vr = eig(PrM,left=True)

result_av = np.array(vl[:,0]/sum(vl[:,0]))

print(result_av)

[0.17126332+0.j 0.16658525+0.j 0.32229129+0.j 0.16658525+0.j
 0.17327489+0.j]


In [171]:
resultados = [result_rw,result_passo,result_av]

for r in range(len(resultados)):
  print(resultados[r]/resultados[(r+1)%len(resultados)])
  

[[0.9988829  0.99634869 1.0002163  1.00214753 1.00214754]]
[[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]]
[1.00111835+0.j 1.00366469+0.j 0.99978375+0.j 0.99785708+0.j
 0.99785707+0.j]
