<a href="https://colab.research.google.com/github/biemt-pesc-coppe-ufrj/exemplosXexeo/blob/master/bimt_hits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import numpy as np

L = np.array([[0, 0, 1, 0, 1],[1, 0, 1, 0, 0],[0, 1, 0, 1, 0],[1, 0, 0, 0, 1],[0, 0, 1, 0, 0]])
n = L.shape[0]
hubs = np.ones(n)
auts = np.ones(n)

In [146]:
print(L,n,hubs,auts)

[[0 0 1 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 0 1 0 0]] 5 [1. 1. 1. 1. 1.] [1. 1. 1. 1. 1.]


In [147]:
def hits_matrixes(L):
    LT = L.transpose()
    AUT = LT.dot(L)
    HUB = L.dot(LT)
    return AUT,HUB



In [148]:
AUT,HUB = hits_matrixes(L)
print(AUT)
print(HUB)

[[2 0 1 0 1]
 [0 1 0 1 0]
 [1 0 3 0 1]
 [0 1 0 1 0]
 [1 0 1 0 2]]
[[2 1 0 1 1]
 [1 2 0 1 1]
 [0 0 2 0 0]
 [1 1 0 2 0]
 [1 1 0 0 1]]


# HITS como o livro acha o resultado

In [149]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)
epsilon = np.ones(n)/1000000
auts = np.ones(n)
hubs = np.ones(n)
while True:
  auts_old = auts
  hubs_old = hubs
  auts = LT.dot(hubs)
  hubs = L.dot(auts)
  norma = 0
  for i in auts:
    norma += i
  normh = 0
  for j in hubs:
    normh += j
  auts /= norma #max(auts)
  hubs /= normh #max(hubs)
  print(auts,hubs)
  if  (((abs(hubs - hubs_old)) < epsilon).all()) and \
      (((abs(auts - auts_old)) < epsilon).all()):
    break

[0.222 0.111 0.333 0.111 0.222] [0.263 0.263 0.105 0.211 0.158]
[0.257 0.057 0.371 0.057 0.257] [0.278 0.278 0.051 0.228 0.165]
[0.276 0.028 0.393 0.028 0.276] [0.286 0.286 0.024 0.236 0.168]
[0.285 0.013 0.404 0.013 0.285] [0.29  0.29  0.011 0.24  0.17 ]
[0.289 0.006 0.41  0.006 0.289] [0.291 0.291 0.005 0.241 0.171]
[0.291 0.003 0.412 0.003 0.291] [0.292 0.292 0.002 0.242 0.171]
[0.292 0.001 0.413 0.001 0.292] [0.293 0.293 0.001 0.242 0.171]
[0.293 0.001 0.414 0.001 0.293] [0.293 0.293 0.    0.243 0.171]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
[0.293 0.    0.414 0.    0.293] [0.293 0

In [150]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)
epsilon = np.ones(n)/1000000
auts = np.ones(n)
hubs = np.ones(n)
while True:
  auts_old = auts
  hubs_old = hubs
  auts = LT.dot(hubs)
  hubs = L.dot(auts)
  norma = np.linalg.norm(auts)
  normh = np.linalg.norm(hubs)
  auts /= norma 
  hubs /= normh 
  print(auts,hubs)
  if  (((abs(hubs - hubs_old)) < epsilon).all()) and \
      (((abs(auts - auts_old)) < epsilon).all()):
    break

[0.459 0.229 0.688 0.229 0.459] [0.563 0.563 0.225 0.45  0.338]
[0.489 0.109 0.706 0.109 0.489] [0.572 0.572 0.104 0.468 0.338]
[0.497 0.05  0.708 0.05  0.497] [0.574 0.574 0.047 0.474 0.337]
[0.499 0.023 0.708 0.023 0.499] [0.575 0.575 0.021 0.475 0.337]
[0.5   0.01  0.707 0.01  0.5  ] [0.575 0.575 0.01  0.476 0.337]
[0.5   0.005 0.707 0.005 0.5  ] [0.575 0.575 0.004 0.476 0.337]
[0.5   0.002 0.707 0.002 0.5  ] [0.575 0.575 0.002 0.476 0.337]
[0.5   0.001 0.707 0.001 0.5  ] [0.575 0.575 0.001 0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0.575 0.    0.476 0.337]
[0.5   0.    0.707 0.    0.5  ] [0.575 0

In [151]:
def power(A,x):
  return A.dot(x.transpose())


def powerk(A,k,x):
  AK = A
  for i in range(k-1):
    AK = AK.dot(A)
  R = AK.dot(x.transpose())
  norma = np.linalg.norm(R)
  return R/norma

def powerk2(A,k,x):
  AK = A
  for i in range(k-1):
    AK = AK.dot(A)
  R = AK.dot(x.transpose())
  soma = 0
  for i in R:
    soma += i
  return R/soma

In [152]:
import math
S = np.array([1, 1, 1, 1, 1])
S1 = S.copy()
for i in range(5):
  S = power(AUT,S.transpose())
  norma = 0
  for value in S:
    norma += value**2
  print(norma)
  norma = math.sqrt(norma)
  #if i %10 == 0:
  print(S/norma)
print(powerk(AUT,15,S1))
print(powerk2(AUT,15,S1))

65
[0.496 0.248 0.62  0.248 0.496]
1139
[0.504 0.119 0.682 0.119 0.504]
21689
[0.502 0.054 0.699 0.054 0.502]
420611
[0.501 0.025 0.705 0.025 0.501]
8187737
[0.5   0.011 0.706 0.011 0.5  ]
[0.5   0.    0.707 0.    0.5  ]
[0.293 0.    0.414 0.    0.293]


In [153]:
A = np.array([[2, -12],[1, -5]])
x = np.array([1, 1]).transpose()
y = x.copy()
for i in range(30):
  x=power(A,x)
  print(x,x/min(x))
a = powerk(A,30,y)
print(a/min(a))

[-10  -4] [1.  0.4]
[28 10] [2.8 1. ]
[-64 -22] [1.    0.344]
[136  46] [2.957 1.   ]
[-280  -94] [1.    0.336]
[568 190] [2.989 1.   ]
[-1144  -382] [1.    0.334]
[2296  766] [2.997 1.   ]
[-4600 -1534] [1.    0.333]
[9208 3070] [2.999 1.   ]
[-18424  -6142] [1.    0.333]
[36856 12286] [3. 1.]
[-73720 -24574] [1.    0.333]
[147448  49150] [3. 1.]
[-294904  -98302] [1.    0.333]
[589816 196606] [3. 1.]
[-1179640  -393214] [1.    0.333]
[2359288  786430] [3. 1.]
[-4718584 -1572862] [1.    0.333]
[9437176 3145726] [3. 1.]
[-18874360  -6291454] [1.    0.333]
[37748728 12582910] [3. 1.]
[-75497464 -25165822] [1.    0.333]
[150994936  50331646] [3. 1.]
[-301989880 -100663294] [1.    0.333]
[603979768 201326590] [3. 1.]
[-1207959544  -402653182] [1.    0.333]
[2415919096  805306366] [3. 1.]
[-4831838200 -1610612734] [1.    0.333]
[9663676408 3221225470] [3. 1.]
[3. 1.]
