In [ ]:
import numpy as np

L = np.array([[0, 0, 1, 0, 1],[1, 0, 1, 0, 0],[0, 1, 0, 1, 0],[1, 0, 0, 0, 1],[0, 0, 1, 0, 0]])
n = L.shape[0]

hubs = np.ones(n)
auts = np.ones(n)

ERROR = 10000000
NORM = 1 # sum of abs 

In [ ]:
DEF_SIZE = 50

def center(s,size=DEF_SIZE):
  tam = (size - len(s))//2
  return " "*tam+s

def print_line(char="=",size=DEF_SIZE):
  print(char*size)

In [ ]:
print_line()
print(center("L"))
print(L)
print_line("-")
print(f"n = {n}")
print_line("-")
print(center("hubs e auts"))
print(hubs,auts)

                        L
[[0 0 1 0 1]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [1 0 0 0 1]
 [0 0 1 0 0]]
--------------------------------------------------
n = 5
--------------------------------------------------
                   hubs e auts
[1. 1. 1. 1. 1.] [1. 1. 1. 1. 1.]


In [ ]:

def hits_matrixes(L):
    LT = L.transpose()
    AUT = LT.dot(L)
    HUB = L.dot(LT)
    return AUT,HUB,LT



In [ ]:

AUT,HUB,LT = hits_matrixes(L)



In [ ]:
print_line()
print(center("AUT"))
print(AUT)
print(center("HUB"))
print(HUB)
print(center("LT"))
print(LT)

                       AUT
[[2 0 1 0 1]
 [0 1 0 1 0]
 [1 0 3 0 1]
 [0 1 0 1 0]
 [1 0 1 0 2]]
                       HUB
[[2 1 0 1 1]
 [1 2 0 1 1]
 [0 0 2 0 0]
 [1 1 0 2 0]
 [1 1 0 0 1]]
                        LT
[[0 1 0 1 0]
 [0 0 1 0 0]
 [1 1 0 0 1]
 [0 0 1 0 0]
 [1 0 0 1 0]]


# HITS como o livro acha o resultado


In [ ]:
# controlando a impressão de números

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)


# erro admitido
epsilon = np.ones(n)/ERROR

# no início os vetores são unitários
auts = np.ones(n)
hubs = np.ones(n)

print_line(size=80)
print(center("norma calculada ||1",80))

passo = 0
while True:
  passo += 1
  auts_old = auts # guarda para calcular o erro
  hubs_old = hubs
  auts = LT.dot(hubs) # conta básica
  hubs = L.dot(auts)

  norma = 0 # calcula normas || ||1 
  for i in auts:
    norma += abs(i)
  normh = 0
  for j in hubs:
    normh += abs(j)
  auts /= norma #max(auts)
  hubs /= normh #max(hubs)

  print(f"passo {passo:2d} {auts} {hubs}")  #verifica se chegou no erro admitido
  if  (((abs(hubs - hubs_old)) < epsilon).all()) and \
      (((abs(auts - auts_old)) < epsilon).all()):
    break

print_line("-",80)
print(center("resultado",size=80))
print(auts,hubs)

                              norma calculada ||1
passo  1 [0.222 0.111 0.333 0.111 0.222] [0.263 0.263 0.105 0.211 0.158]
passo  2 [0.257 0.057 0.371 0.057 0.257] [0.278 0.278 0.051 0.228 0.165]
passo  3 [0.276 0.028 0.393 0.028 0.276] [0.286 0.286 0.024 0.236 0.168]
passo  4 [0.285 0.013 0.404 0.013 0.285] [0.29  0.29  0.011 0.24  0.17 ]
passo  5 [0.289 0.006 0.41  0.006 0.289] [0.291 0.291 0.005 0.241 0.171]
passo  6 [0.291 0.003 0.412 0.003 0.291] [0.292 0.292 0.002 0.242 0.171]
passo  7 [0.292 0.001 0.413 0.001 0.292] [0.293 0.293 0.001 0.242 0.171]
passo  8 [0.293 0.001 0.414 0.001 0.293] [0.293 0.293 0.    0.243 0.171]
passo  9 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 10 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 11 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 12 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 13 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
p

In [ ]:
# mesmo programa que o anterior usando agora a norma do np

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

epsilon = np.ones(n)/ERROR

auts = np.ones(n)
hubs = np.ones(n)

print_line(size=80)
print(center("norma nympy linalg",80))


while True:
  auts_old = auts
  hubs_old = hubs
  auts = LT.dot(hubs)
  hubs = L.dot(auts)

  norma = np.linalg.norm(auts,ord=NORM)
  normh = np.linalg.norm(hubs,ord=NORM)
  auts /= norma 
  hubs /= normh 

  print(f"passo {passo:2d} {auts} {hubs}")  #verifica se chegou no erro admitido
  if  (((abs(hubs - hubs_old)) < epsilon).all()) and \
      (((abs(auts - auts_old)) < epsilon).all()):
    break


print_line("-",80)
print(center("resultado",size=80))
print(auts,hubs)   



                               norma nympy linalg
passo 20 [0.222 0.111 0.333 0.111 0.222] [0.263 0.263 0.105 0.211 0.158]
passo 20 [0.257 0.057 0.371 0.057 0.257] [0.278 0.278 0.051 0.228 0.165]
passo 20 [0.276 0.028 0.393 0.028 0.276] [0.286 0.286 0.024 0.236 0.168]
passo 20 [0.285 0.013 0.404 0.013 0.285] [0.29  0.29  0.011 0.24  0.17 ]
passo 20 [0.289 0.006 0.41  0.006 0.289] [0.291 0.291 0.005 0.241 0.171]
passo 20 [0.291 0.003 0.412 0.003 0.291] [0.292 0.292 0.002 0.242 0.171]
passo 20 [0.292 0.001 0.413 0.001 0.292] [0.293 0.293 0.001 0.242 0.171]
passo 20 [0.293 0.001 0.414 0.001 0.293] [0.293 0.293 0.    0.243 0.171]
passo 20 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 20 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 20 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 20 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
passo 20 [0.293 0.    0.414 0.    0.293] [0.293 0.293 0.    0.243 0.172]
p

In [ ]:
def power(A,x):
  return A.dot(x.transpose())


# potencia com a norma linalg
def powerk(A,k,x):
  AK = A
  for i in range(k-1):
    AK = AK.dot(A)
  R = AK.dot(x.transpose())
  norma = np.linalg.norm(R,ord=NORM)
  return R/norma

# potencia com a norma calculada
def powerk2(A,k,x):
  AK = A
  for i in range(k-1):
    AK = AK.dot(A)
  R = AK.dot(x.transpose())
  soma = 0
  for i in R:
    soma += i
  return R/soma

In [ ]:
import math
S = np.array([1, 1, 1, 1, 1])
S1 = S.copy()
for i in range(5):
  S = power(AUT,S.transpose())
  norma = 0
  for value in S:
    norma += value**2
  norma = math.sqrt(norma)
  #if i %10 == 0:
  print(S/norma)


[0.496 0.248 0.62  0.248 0.496]
[0.504 0.119 0.682 0.119 0.504]
[0.502 0.054 0.699 0.054 0.502]
[0.501 0.025 0.705 0.025 0.501]
[0.5   0.011 0.706 0.011 0.5  ]


In [ ]:
print_line()
print(center("powerk"))
print(powerk(AUT,15,S1))
print(center("powerk2"))
print(powerk2(AUT,15,S1))



                      powerk
[0.293 0.    0.414 0.    0.293]
                     powerk2
[0.293 0.    0.414 0.    0.293]
